# @version 0.1.0 #1 Initialize environment
#
# @author Dallas Vogels <dvogels@islandlinux.org>
#
# @copyright (c) 2016 Dallas Vogels <dvogels@islandlinux.org>
language: node_js

node_js:
  - '0.10'

install:
  - 'npm install -g npm@2'
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'

notifications:
  email:
    recipients:
      - dvogels@islandlinux.org
    on_success: change
    on_failure: always

